// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4xSTW/bMAz9KwK3o1FnXxffOhQYchu6ATsUPagSnbCwJY2iUwSB//tA2bGbdd12SSzz",
	"+el98AQu9ikGDJKhOUF2e+xtefyC8iOyv8U8dKIvEseELIRlfIMtBRKKoRxJsC8PbxlbaOBNvRLXM2t9",
	"QbkSwFiBHBNCA5bZHvWsOKXzmB1TKrAGvu/RPEX25gEp7AyjMOEB/RUsDFmYwg7GsQLGnwMxemjuJr7q",
	"QvX98k18eEQneu1rCv9i/88q/TI3sTUy6/63zme8L/UpmEIb9Uoh6XR2Q07Rlo/mG/KBHJrrr1uo4ICc",
	"Jz3vrjZXG3UXEwabCBr4UF5VkKzsi59a5dUn/R31vEN5aex2ztt4FEtdNjb4Z06zaSMba3Z0wLD41dSs",
	"jrcemnPAcx3Jsu1RkDM0d6+WLXFperm5jazkpEA1ARUE22sgTxP1GqrwgNW82SW53wq4V3BOMeSp2veb",
	"jf65GARDScGm1JErJurHPFW+8v33xk8FXpq8NnlwDnNuh86cZWhXHycVl+jP1hs1hrls66cVQ3zGbIMg",
	"B9uZjHxANsgcuexZHvre8nFqYYp2jlOVjb8CAAD///A6NxYMBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
